files:
  - source: /src/main/resources/texts
    ignore:
      - /src/main/resources/texts_%locale_with_underscore%.properties
    translation: /src/main/resources/texts_%locale_with_underscore%.properties
